Capycom/Controllers/PostCommentController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using Capycom.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.Extensions.Hosting;
using System.Data.Common;
using Microsoft.EntityFrameworkCore;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory;
using System.Reflection.Metadata;
using System.Security.Claims;
using Serilog;
using Microsoft.Extensions.FileSystemGlobbing;

namespace Capycom.Controllers
{
    public class PostCommentController : Controller
    {
        private readonly CapycomContext _context;
        private readonly MyConfig _config;
        private readonly ILogger<PostCommentController> _logger;

        public PostCommentController(ILogger<PostCommentController> logger, CapycomContext context, IOptions<MyConfig> config)
        {
            _context = context;
            _config = config.Value;
            _logger = logger;
        }
        public async Task<IActionResult> ViewPost(Guid postId)
        {
            if(User.Identity.IsAuthenticated)
                Log.Information("Пользователь {User} просматривает пост {Post}", HttpContext.User.FindFirstValue("CpcmUserId"), postId);
            else
                Log.Information("Неавторизирвоанный клиент {@client} просматривает пост {Post}",HttpContext.Connection, postId);

            try
            {
                CpcmPost? post = await _context.CpcmPosts.Where(p => p.CpcmPostId == postId).Include(p => p.CpcmImages).Include(p => p.CpcmPostFatherNavigation).ThenInclude(p => p.CpcmImages).FirstOrDefaultAsync();
                if(post == null || post.CpcmIsDeleted)
                {
                    Log.Information("Попытка просмотра несуществующего поста {Post}", postId);
                    Response.StatusCode = 404;
                    ViewData["ErrorCode"] = 404;
                    ViewData["Message"] = "Пост не найден";
                    return View("UserError");
                }
                post.User = await _context.CpcmUsers.Where(u => u.CpcmUserId == post.CpcmUserId).FirstOrDefaultAsync();
                post.Group = await _context.CpcmGroups.Where(g => g.CpcmGroupId == post.CpcmGroupId).FirstOrDefaultAsync();
                //if (post.CpcmPostBanned)
                //{
                //    Log.Information("Попытка просмотра заблокированного поста {Post}", postId);
                //    Response.StatusCode = 403;
                //    ViewData["ErrorCode"] = 403;
                //    ViewData["Message"] = "Пост заблокирован";
                //    return View("UserError");
                //}
                if (post.User == null || post.User.CpcmIsDeleted)
                {
					Log.Information("Попытка просмотра поста удалённого Юзера {Post}", postId);
					Response.StatusCode = 404;
					ViewData["ErrorCode"] = 404;
					ViewData["Message"] = "Пост не найден";
					return View("UserError");
				}
                if (post.User != null && post.User.CpcmUserBanned)
                {
					Log.Information("Попытка просмотра поста заблокированного Юзера {Post}", postId);
					Response.StatusCode = 403;
					ViewData["ErrorCode"] = 403;
					ViewData["Message"] = "Автор поста заблокирован";
                    ViewData["id"] = post.CpcmUserId;
					return View("UserError");
				}
                if (post.User==null)
                {
                    if (post.Group == null || post.Group.CpcmIsDeleted)
                    {
                        Log.Information("Попытка просмотра поста удалённой Группы {Post}", postId);
                        Response.StatusCode = 404;
                        ViewData["ErrorCode"] = 404;
                        ViewData["Message"] = "Пост не найден";
                        return View("UserError");
                    }
                    if ((post.Group != null && post.Group.CpcmGroupBanned))
                    {
                        Log.Information("Попытка просмотра поста заблокированной Группы{Post}", postId);
                        Response.StatusCode = 403;
                        ViewData["ErrorCode"] = 403;
                        ViewData["Message"] = "Группа поста заблокирована";
                        ViewData["id"] = post.CpcmGroupId;
                        return View("UserError");
                    }
					//if (post.CpcmPostPublishedDate > DateTime.UtcNow && GetUserId() != post.CpcmUserId)
					//{
					//	Log.Information("Попытка просмотра отложенного поста {Post}", postId);
					//	Response.StatusCode = 404;
					//	ViewData["ErrorCode"] = 404;
					//	ViewData["Message"] = "Пост не найден";
					//	return View("UserError");
					//}
				}
                else
                {
					if (post.CpcmPostPublishedDate > DateTime.UtcNow && GetUserId() != post.CpcmUserId)
					{
						Log.Information("Попытка просмотра отложенного поста {Post}", postId);
						Response.StatusCode = 404;
						ViewData["ErrorCode"] = 404;
						ViewData["Message"] = "Пост не найден";
						return View("UserError");
					}
				}

                var topComments = await _context.CpcmComments.Where(p => p.CpcmPostId == post.CpcmPostId && p.CpcmCommentFather == null && !p.CpcmIsDeleted).Include(c => c.CpcmImages).Include(c => c.CpcmUser).OrderByDescending(u => u.CpcmCommentCreationDate).Take(10).ToListAsync(); // впринципе эту итерацию можно пихнуть сразу в тот метод
                foreach (var TopComment in topComments)
                {
                    TopComment.InverseCpcmCommentFatherNavigation = await GetCommentChildrenReccurent(TopComment);
					if (HttpContext.Request.Cookies.ContainsKey("TimeZone"))
					{
						string timezoneOffsetCookie = HttpContext.Request.Cookies["TimeZone"];
						if (timezoneOffsetCookie != null)
						{
							if (int.TryParse(timezoneOffsetCookie, out int timezoneOffsetMinutes))
							{
								TimeSpan offset = TimeSpan.FromMinutes(timezoneOffsetMinutes);
								if (offset.TotalHours <= 24)
								{
									TopComment.CpcmCommentCreationDate -= offset;
								}


							}
						}
					}
				}
                if(post.CpcmPostFatherNavigation != null)
                {
                    post.CpcmPostFatherNavigation = await GetFatherPostReccurent(post);
                }
                CpcmUser? userOwner = await _context.CpcmUsers.Where(u => u.CpcmUserId == post.CpcmUserId).FirstOrDefaultAsync();
                CpcmGroup? groupOwner = await _context.CpcmGroups.Where(u => u.CpcmGroupId == post.CpcmGroupId).FirstOrDefaultAsync();
				if (User.Identity.IsAuthenticated && groupOwner != null )
				{
					var authUserId = GetUserId();
					var authFollower = await _context.CpcmGroupfollowers.Where(f => f.CpcmUserId == authUserId && f.CpcmGroupId == groupOwner.CpcmGroupId).Include(f => f.CpcmUserRoleNavigation).FirstOrDefaultAsync();
                    groupOwner.UserFollowerRole = authFollower.CpcmUserRoleNavigation;
                    post.Group.UserFollowerRole = authFollower.CpcmUserRoleNavigation;
				}
				long likes = await _context.Database.SqlQuery<long>($@"SELECT * FROM CPCM_POSTLIKES WHERE CPCM_PostID = {post.CpcmPostId}").CountAsync();
                long reposts = await _context.Database.SqlQuery<long>($@"SELECT * FROM CPCM_POSTREPOSTS WHERE CPCM_PostID = {post.CpcmPostId}").CountAsync();

				if (User.Identity.IsAuthenticated)
				{
					long liked = await _context.Database.SqlQuery<long>($@"SELECT * FROM CPCM_POSTLIKES WHERE CPCM_PostID = {post.CpcmPostId} AND CPCM_UserID = {post.CpcmUserId}").CountAsync();
					if (liked > 0)
						post.IsLiked = true;
					else
						post.IsLiked = false;
				}

				if (HttpContext.Request.Cookies.ContainsKey("TimeZone"))
				{
					string timezoneOffsetCookie = HttpContext.Request.Cookies["TimeZone"];
					if (timezoneOffsetCookie != null)
					{
						if (int.TryParse(timezoneOffsetCookie, out int timezoneOffsetMinutes))
						{
							TimeSpan offset = TimeSpan.FromMinutes(timezoneOffsetMinutes);
							if (offset.TotalHours <= 24)
							{
								post.CpcmPostPublishedDate -= offset;
							}
							

						}
					}
				}


				PostModel postModel = new() { Post=post,UserOwner=userOwner, GroupOwner = groupOwner, LikesCount=likes,RepostsCount=reposts, TopLevelComments=topComments};
                return View(postModel);
            }
            catch(DbUpdateException ex)
            {
				Log.Error(ex, "Не удалось выполнить запрос к БД на выборку поста {Post}", postId);
				Response.StatusCode = 500;
				ViewData["ErrorCode"] = 500;
				ViewData["Message"] = "Ошибка связи с сервером";
				return View("UserError");
			}
            catch (DbException ex )
            {
                Log.Error(ex,"Не удалось выполнить запрос к БД на выборку поста {Post}", postId);
                Response.StatusCode = 500;
                ViewData["ErrorCode"] = 500;
                ViewData["Message"] = "Ошибка связи с сервером";
                return View("UserError");
            }
        }

        [Authorize]
        public async Task<IActionResult> AddComment(CommentAddModel userComment)
        {
            if (!_config.AllowCreateComment)
            {
                return RedirectToAction("Index", "Home");
            }
            try
            {
                var post = await _context.CpcmPosts.Where(p => p.CpcmPostId == userComment.CpcmPostId).FirstOrDefaultAsync();
                if(post == null || post.CpcmIsDeleted)
                {   
                    Log.Warning("Пользователь {User} пытается добавить комментарий к несуществующему посту {Post}", HttpContext.User.FindFirstValue("CpcmUserId"), userComment.CpcmPostId);
					return StatusCode(404);
				}
                post.User = await _context.CpcmUsers.Where(u => u.CpcmUserId == post.CpcmUserId).FirstOrDefaultAsync();
                post.Group = await _context.CpcmGroups.Where(g => g.CpcmGroupId == post.CpcmGroupId).FirstOrDefaultAsync();
                if (post.CpcmPostBanned)
                {

Capycom/Views/PostComment/AddComment.cshtml
@model CpcmComment

<div class="card mt-2" id="@Model.CpcmCommentId">
	<div class="d-flex">
		@if (Model.CpcmUser.CpcmIsDeleted)
		{
			<p class="m-1 pb-1">Аккаунт автора комментария был удалён :(</p>
		}
		else if (Model.CpcmUser.CpcmUserBanned)
		{
			<p class="m-1 pb-1">Автор комментария был забаннен :(</p>
		}
		else if (Model.CpcmIsDeleted)
		{
			<p class="m-1 pb-1">Комментарий удалён :(</p>
		}
		else if (Model.CpcmCommentBanned)
		{
			<p class="m-1 pb-1">Комментарий забаннен :(</p>
		}
		else
		{
			@if (Model.CpcmUser.CpcmUserNickName != null)
			{
				<a asp-controller="User" asp-action="Index" asp-route-Nickname="@Model.CpcmUser.CpcmUserNickName">
					@if (Model.CpcmUser.CpcmUserImagePath != string.Empty)
					{
						<img src="@Url.Content(@Model.CpcmUser?.CpcmUserImagePath)"
							 class="rounded-circle mt-2 ms-2 me-2 user-icon">
					}
					else
					{
						<img src="\images\default.png"
							 class="rounded-circle mt-2 ms-2 me-2 user-icon">
					}

				</a>
			}
			else
			{
				<a asp-controller="User" asp-action="Index" asp-route-UserId="@Model.CpcmUser.CpcmUserId">
					<img src="@Url.Content(@Model.CpcmUser?.CpcmUserImagePath)"
						 class="rounded-circle mt-2 ms-2 me-2 user-icon">
				</a>
			}
			<div class="row p-1">
				@if (@Model.CpcmUser?.CpcmUserNickName != null)
				{
					<div>
						<a class="mt-0 mb-0 link-dark nickname" asp-controller="User" asp-action="Index" asp-route-Nickname="@Model.CpcmUser.CpcmUserNickName">
							@Model.CpcmUser?.CpcmUserFirstName @Model.CpcmUser?.CpcmUserSecondName @Model.CpcmUser?.CpcmUserAdditionalName
						</a>
					</div>
				}
				else
				{
					<div>
						<a class="mt-0 mb-0 link-dark nickname" asp-controller="User" asp-action="Index" asp-route-UserId="@Model.CpcmUser.CpcmUserId" class="mt-0 mb-0">
							@Model.CpcmUser?.CpcmUserFirstName @Model.CpcmUser?.CpcmUserSecondName @Model.CpcmUser?.CpcmUserAdditionalName
						</a>
					</div>
				}
				<a asp-controller="PostComment" asp-action="ViewComment" asp-route-commentId="@Model.CpcmCommentId" class="text-muted">@Model.CpcmCommentCreationDate.ToString("dd.MM.yyyy hh:mm")</a>
				<p class="mb-1">@Model.CpcmCommentText</p>
			</div>
			@if (User.Identity.IsAuthenticated && Model.CpcmUser.CpcmUserId.ToString() == User.FindAll(x => x.Type == "CpcmUserId").FirstOrDefault().Value)
			{
				<div class="ms-auto mb-auto me-1 d-flex" style="flex-direction: column;">
					@*
			<a asp-controller="User" asp-action="EditPost" asp-route-postGuid="@Model.Post.CpcmPostId">
			<img src="~/images/pencil-square.svg" />
			</a>
			*@
					<a style="cursor: pointer;" data-bs-toggle="modal" data-bs-target="#confirmDeleteModal" onclick="askCommentDelete('@Model.CpcmCommentId')">
						<svg class="text-danger" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash3" viewBox="0 0 16 16">
							<path d="M6.5 1h3a.5.5 0 0 1 .5.5v1H6v-1a.5.5 0 0 1 .5-.5M11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3A1.5 1.5 0 0 0 5 1.5v1H1.5a.5.5 0 0 0 0 1h.538l.853 10.66A2 2 0 0 0 4.885 16h6.23a2 2 0 0 0 1.994-1.84l.853-10.66h.538a.5.5 0 0 0 0-1zm1.958 1-.846 10.58a1 1 0 0 1-.997.92h-6.23a1 1 0 0 1-.997-.92L3.042 3.5zm-7.487 1a.5.5 0 0 1 .528.47l.5 8.5a.5.5 0 0 1-.998.06L5 5.03a.5.5 0 0 1 .47-.53Zm5.058 0a.5.5 0 0 1 .47.53l-.5 8.5a.5.5 0 1 1-.998-.06l.5-8.5a.5.5 0 0 1 .528-.47M8 4.5a.5.5 0 0 1 .5.5v8.5a.5.5 0 0 1-1 0V5a.5.5 0 0 1 .5-.5" />
						</svg>
					</a>
				</div>
			}
		}
	</div>
	<div class="row row-cols-1 ps-2 pb-1 @(Model.CpcmImages.Count > 1 ? "row-cols-md-2 row-cols-lg-2" : "") g-2">
		@foreach (var image in Model.CpcmImages)
		{
			<div class="col block-image">
				<img src="@Url.Content(@image.CpcmImagePath)" class="rounded card-img-top object-fit-cover h-100 mt-0" alt="Изображение">
			</div>
		}
	</div>
</div>

Capycom/Views/PostComment/Comment.cshtml
@model ICollection<CpcmComment>
@foreach (var comment in Model)
{
	<div class="card mt-2 comment" id="@comment.CpcmCommentId">
		<div class="d-flex">

			@if (comment.CpcmUser.CpcmUserNickName != null)
			{
				<a asp-controller="User" asp-action="Index" asp-route-Nickname="@comment.CpcmUser.CpcmUserNickName">
					@if (comment.CpcmUser.CpcmIsDeleted || comment.CpcmUser.CpcmUserBanned)
					{
						<img src="\images\default-banned.png"
							 class="rounded-circle mt-2 ms-2 me-2 user-icon">
					}
					else if (comment.CpcmUser.CpcmUserImagePath != null && comment.CpcmUser.CpcmUserImagePath != string.Empty)
					{
						<img src="@Url.Content(@comment.CpcmUser?.CpcmUserImagePath)"
							 class="rounded-circle mt-2 ms-2 me-2 user-icon">
					}
					else
					{
						<img src="\images\default.png"
							 class="rounded-circle mt-2 ms-2 me-2 user-icon">
					}
				</a>
			}
			else
			{
				<a asp-controller="User" asp-action="Index" asp-route-UserId="@comment.CpcmUser.CpcmUserId">
					@if (comment.CpcmUser.CpcmIsDeleted || comment.CpcmUser.CpcmUserBanned)
					{
						<img src="\images\default-banned.png"
							 class="rounded-circle mt-2 ms-2 me-2 user-icon">
					}
					else if (comment.CpcmUser.CpcmUserImagePath != null && comment.CpcmUser.CpcmUserImagePath != string.Empty)
					{
						<img src="@Url.Content(@comment.CpcmUser?.CpcmUserImagePath)"
							 class="rounded-circle mt-2 ms-2 me-2 user-icon">
					}
					else
					{
						<img src="\images\default.png"
							 class="rounded-circle mt-2 ms-2 me-2 user-icon">
					}
				</a>
			}
			<div class="p-1">
				@if (@comment.CpcmUser?.CpcmUserNickName != null)
				{
					<div>
						<a class="mt-0 mb-0 link-dark nickname" asp-controller="User" asp-action="Index" asp-route-Nickname="@comment.CpcmUser.CpcmUserNickName">
							@comment.CpcmUser?.CpcmUserFirstName @comment.CpcmUser?.CpcmUserSecondName @comment.CpcmUser?.CpcmUserAdditionalName
						</a>
					</div>
				}
				else
				{
					<div>
						<a class="mt-0 mb-0 link-dark nickname" asp-controller="User" asp-action="Index" asp-route-UserId="@comment.CpcmUser.CpcmUserId" class="mt-0 mb-0">
							@comment.CpcmUser?.CpcmUserFirstName @comment.CpcmUser?.CpcmUserSecondName @comment.CpcmUser?.CpcmUserAdditionalName
						</a>
					</div>
				}
				<a asp-controller="PostComment" asp-action="ViewComment" asp-route-commentId="@comment.CpcmCommentId" class="text-muted">@comment.CpcmCommentCreationDate.ToString("dd.MM.yyyy hh:mm")</a>
				<p class="mb-1 comment-text">
					@if (comment.CpcmUser.CpcmIsDeleted)
					{
						<i class="m-1 pb-1">Аккаунт автора комментария был удалён :(</i>
					}
					else if (comment.CpcmUser.CpcmUserBanned)
					{
						<i class="m-1 pb-1">Автор комментария был забаннен :(</i>
					}
					else if (comment.CpcmIsDeleted)
					{
						<i class="m-1 pb-1">Комментарий удалён :(</i>
					}
					else if (comment.CpcmCommentBanned)
					{
						<i class="m-1 pb-1">Комментарий забаннен :(</i>
					}
					else
					{
						@comment.CpcmCommentText
					}
				</p>
				@if (!comment.CpcmUser.CpcmIsDeleted && !comment.CpcmUser.CpcmUserBanned && !comment.CpcmIsDeleted && !comment.CpcmCommentBanned)
				{
					<div class="row row-cols-1 ps-2 pb-1 @(comment.CpcmImages.Count > 1 ? "row-cols-md-2 row-cols-lg-2" : "") g-2">
						@foreach (var image in comment.CpcmImages)
						{
							<div class="col block-image">
								<img src="@Url.Content(@image.CpcmImagePath)" class="rounded card-img-top object-fit-cover h-100 mt-0" alt="Изображение">
						</div>
					}
				</div>
				}
			</div>
			<div class="ms-auto mb-auto me-1 d-flex" style="flex-direction: column;">
				@if (User.Identity.IsAuthenticated && comment.CpcmUser.CpcmUserId.ToString() == User.FindAll(x => x.Type == "CpcmUserId").FirstOrDefault().Value)
				{
					<a style="cursor: pointer;" data-bs-toggle="modal" data-bs-target="#confirmDeleteModal" onclick="askCommentDelete('@comment.CpcmCommentId')">
						<svg class="text-danger" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash3" viewBox="0 0 16 16">
							<path d="M6.5 1h3a.5.5 0 0 1 .5.5v1H6v-1a.5.5 0 0 1 .5-.5M11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3A1.5 1.5 0 0 0 5 1.5v1H1.5a.5.5 0 0 0 0 1h.538l.853 10.66A2 2 0 0 0 4.885 16h6.23a2 2 0 0 0 1.994-1.84l.853-10.66h.538a.5.5 0 0 0 0-1zm1.958 1-.846 10.58a1 1 0 0 1-.997.92h-6.23a1 1 0 0 1-.997-.92L3.042 3.5zm-7.487 1a.5.5 0 0 1 .528.47l.5 8.5a.5.5 0 0 1-.998.06L5 5.03a.5.5 0 0 1 .47-.53Zm5.058 0a.5.5 0 0 1 .47.53l-.5 8.5a.5.5 0 1 1-.998-.06l.5-8.5a.5.5 0 0 1 .528-.47M8 4.5a.5.5 0 0 1 .5.5v8.5a.5.5 0 0 1-1 0V5a.5.5 0 0 1 .5-.5" />
						</svg>
					</a>
				}
				@if (User.Identity.IsAuthenticated && User.FindFirst(c => c.Type == "CpcmCanBanUsersComment").Value == "True")
				{
					if (!comment.CpcmCommentBanned)
					{
						<a class="ban-icon-link" onclick="banComment('/PostComment/BanUnbanComment', '@comment.CpcmCommentId')">
							<svg class="ban-icon" style="color: #dc3545" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-ban" viewBox="0 0 16 16">
								<path d="M15 8a6.97 6.97 0 0 0-1.71-4.584l-9.874 9.875A7 7 0 0 0 15 8M2.71 12.584l9.874-9.875a7 7 0 0 0-9.874 9.874ZM16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0" />
							</svg>
						</a>
					}
					else
					{
						<a class="ban-icon-link" onclick="banComment('/PostComment/BanUnbanComment', '@comment.CpcmCommentId')">
							<svg class="ban-icon" style="color: #198754" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-ban" viewBox="0 0 16 16">
								<path d="M15 8a6.97 6.97 0 0 0-1.71-4.584l-9.874 9.875A7 7 0 0 0 15 8M2.71 12.584l9.874-9.875a7 7 0 0 0-9.874 9.874ZM16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0" />
							</svg>
						</a>
					}
				}
			</div>
		</div>
		@if (comment.InverseCpcmCommentFatherNavigation?.Count != 0)
		{
			<div class="m-1 mt-0">
				@await Html.PartialAsync("Comment", comment.InverseCpcmCommentFatherNavigation)
			</div>
		}
		<a class="me-auto text-muted mb-1 ms-1" onclick="answerComment('@comment.CpcmCommentId', this)" style="cursor:pointer;">Ответить</a>
		<div class="card border-0 m-1 commentCard" style="display:none;">
			<form class="commentForm" method="post" enctype="multipart/form-data">
				@Html.AntiForgeryToken()
				<div class="row mt-auto mb-auto mt-1 mb-1 me-1">
					<div class="col d-flex align-items-center">
						<img src='@Url.Content(Context.Session.GetString("ProfileImage"))' class="rounded-circle m-2 user-icon" style="object-fit: cover;">
						<div class="input-group container-fluid ps-0 pe-0">
							<input name="CpcmCommentFather" value="@comment.CpcmCommentId" hidden />
							<input name="CpcmPostId" value="@comment.CpcmPost.CpcmPostId" hidden />
							<textarea name="CpcmCommentText" type="text" class="form-control comment-text" id="commentText" rows="1" required></textarea>
							<div class="d-flex align-items-center btn btn-light border-top border-bottom">
								<label class="paperclip-label" for="fileInput-@comment.CpcmCommentId">
									<img class="paperclip-icon" src="~/images/paperclip.svg" />
								</label>
							</div>
							<button type="submit" class="btn btn-light border" value="">Отправить</button>
						</div>
						<input name="Files" id="fileInput-@comment.CpcmCommentId" type="file" accept="image/png, image/gif, image/jpeg" onchange="fileLoad(this)" multiple hidden />
					</div>
				</div>
				<div class="row mt-auto mb-auto mt-1 mb-1 me-1">
					<div class="file-list ms-1"></div>
				</div>
			</form>
		</div>
	</div>
}

Capycom/Views/PostComment/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}